name: Deploy MkDocs

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all history is fetched

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-autorefs
          pip install mkdocs-jupyter
          pip install mkdocs-include-markdown-plugin
          pip install mkdocstrings[python]  # Ensure Python support

      - name: Build and Deploy Docs
        run: |
          mkdocs build
          mkdocs gh-deploy --force --remote-branch docs
